# Generated by Django 3.0.6 on 2020-06-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_uri'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uri',
            new_name='Url',
        ),
    ]
