# Generated by Django 3.0.6 on 2020-06-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='send_maill',
            new_name='send_mail',
        ),
    ]
